<a href="https://colab.research.google.com/github/brytlao/Practical_computer_vision/blob/master/CHAPTER_09a_Mathematics_for_Computer_Vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chapter 09a: Mathematics for Computer Vision**

Part 1 of 2 in Chapter 09. Tackles topics on linear algebra.

# **Install and import dependencies**

In [0]:
# helper libraries
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

# **Vectors**

**Definition**

In [0]:
#p = [1,2,3]
p = np.array([1,2,3])

**Length or magnitude**

In [0]:
print("length: {}".format(len(p)))

length: 3


**Addition**

In [0]:
v1 = np.array([2,3,4,5])
v2 = np.array([4,5,6,7])
summ = v1+v2

print("sum: {}".format(summ))

sum: [ 6  8 10 12]


**Subtraction**

In [0]:
v1 = np.array([2,3,4,5])
v2 = np.array([4,5,6,7])
diff = v1-v2

print("difference: {}".format(diff))

difference: [-2 -2 -2 -2]


**Vector multiplication**

In [0]:
v1 = np.array([2,3,4,5])
v2 = np.array([4,5,6,7])

# inner product/dot product
inner = np.inner(v1,v2)
print("inner product: {}".format(inner))

# outer product
outer = np.outer(v1,v2)
print("outer product:\n{}".format(outer))

inner product: 82
outer product:
[[ 8 10 12 14]
 [12 15 18 21]
 [16 20 24 28]
 [20 25 30 35]]


**Vector norm**

In [0]:
v1 = np.array([2,3,4,5])

# l1-norm
norm_l1 = np.linalg.norm(v1,ord=1)
print("l1-norm: {}".format(norm_l1))

# l2-norm
norm_l2 = np.linalg.norm(v1,ord=2)
print("l2-norm: {}".format(norm_l2))

l1-norm: 14.0
l2-norm: 7.3484692283495345


**Orthogonality**

Perpendicular vectors yield a zero inner product.

In [0]:
v1 = np.array([2,3,4,5])
v2 = np.array([-1,1,1,-1]) # orthogonal to v1
inner = np.inner(v1,v2)

# zero inner products
print("v1: {}".format(v1))
print("v2: {}".format(v2))
print("v1 dot v2: {}".format(inner))

v1: [2 3 4 5]
v2: [-1  1  1 -1]
v1 dot v2: 0


# **Matrices**

**Definition**

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix A:\n{}".format(A))

B = np.array([[1,1,1],[1,1,1],[1,1,1]])
print("matrix B:\n{}".format(B))

matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix B:
[[1 1 1]
 [1 1 1]
 [1 1 1]]


**Addition**

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[1,1,1],[1,1,1]])

C = A+B
print("C = A + B:\n{}".format(C))

A + B = C:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**Subtraction**

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[1,1,1],[1,1,1]])

C = A-B
print("C = A - B:\n{}".format(C))

A - B = C:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Matrix multiplication**

In [0]:
A = np.array([[1,2,3],[4,5,6]]) # 2 x 3
B = np.array([[1,0],[0,1],[1,0]]) # 3 x 2

C = np.dot(A,B) # 2 x 2

print("C = AB:\n{}".format(C))

AB = C:
[[ 4  2]
 [10  5]]


**Transpose**

In [0]:
A = np.array([[1,2,3],[4,5,6]])
A_trans = np.transpose(A)

print("matrix A:\n{}".format(A))
print("transpose:\n{}".format(A_trans))

matrix A:
[[1 2 3]
 [4 5 6]]
transpose:
[[1 4]
 [2 5]
 [3 6]]


**Identity matrix**

In [0]:
I = np.identity(3)

print("matrix I:\n{}".format(I))

matrix I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Diagonal matrix**

In [0]:
D = np.array([[1,0,0],[0,2,0],[0,0,3]])

print("matrix D:\n{}".format(D))

matrix D:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


**Symmetric matrix**

In [0]:
# base matrix
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A_trans = np.transpose(A)
print("matrix A:\n{}".format(A))

# symmetric
S = A+A_trans
print("S = A + A_trans:\n{}".format(S))

# anti-symmetric
S_anti = A-A_trans
print("S = A - A_trans:\n{}".format(S_anti))

# base matrix as summation of symmetric and anti-symmetric matrix
summ = 0.5*S + 0.5*S_anti
print("A = 0.5*S + 0.5*S_anti:\n{}".format(summ))

matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
S = A + A_trans:
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
S = A - A_trans:
[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
A = 0.5*S + 0.5*S_anti:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


**Trace of a matrix**

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A_trace = np.trace(A)

print("matrix A:\n{}".format(A))
print("trace of A:\n{}".format(A_trace))

matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
trace of A:
15


**Determinant**

In [0]:
A = np.array([[1,2],[3,4]])
A_det= np.linalg.det(A)

print("matrix A:\n{}".format(A))
print("determinant of A:\n{}".format(A_det))

matrix A:
[[1 2]
 [3 4]]
determinant of A:
-2.0000000000000004


**Norm of a matrix**

In [0]:
A = np.array([[1,2,3],[5,4,6],[9,8,7]])
A_norm = np.linalg.norm(A)

print("matrix A:\n{}".format(A))
print("norm of A:\n{}".format(A_norm))

matrix A:
[[1 2 3]
 [5 4 6]
 [9 8 7]]
norm of A:
16.881943016134134


**Inverse of a matrix**

Product of $A$ and $A^{-1}$ yields an identity matrix

In [0]:
A = np.array([[1,2,3],[5,4,6],[9,8,7]])
A_inv = np.linalg.inv(A)
prod = np.dot(A,A_inv)

print("matrix A:\n{}".format(A))
print("inverse of A:\n{}".format(A_inv))
print("I = A dot A_inv:\n{}".format(prod))

matrix A:
[[1 2 3]
 [5 4 6]
 [9 8 7]]
inverse of A:
[[-6.66666667e-01  3.33333333e-01  4.93432455e-17]
 [ 6.33333333e-01 -6.66666667e-01  3.00000000e-01]
 [ 1.33333333e-01  3.33333333e-01 -2.00000000e-01]]
I = A dot A_inv:
[[ 1.00000000e+00  1.66533454e-16 -5.55111512e-17]
 [ 3.33066907e-16  1.00000000e+00  1.11022302e-16]
 [ 8.32667268e-16 -2.77555756e-16  1.00000000e+00]]


**Orthogonality**

For square matrices, if $A^\top A=I$ and $AA^\top =I$, then $A^\top = A^{-1}$.

In [0]:
A = np.array([[1,0,0],[0,0,1],[0,1,0]])
A_trans = np.transpose(A)
A_inv = np.linalg.inv(A)

# matrix A
print("matrix A:\n{}".format(A))

# A_trans
print("A_trans:\n{}".format(A_trans))

# A_inv
print("A_inv:\n{}".format(A_inv))

# A_trans dot A
ATA = np.dot(A_trans,A)
print("A_trans dot A:\n{}".format(ATA))

# A dot A_trans
AAT = np.dot(A,A_trans)
print("A dot A_trans:\n{}".format(AAT))

matrix A:
[[1 0 0]
 [0 0 1]
 [0 1 0]]
A_trans:
[[1 0 0]
 [0 0 1]
 [0 1 0]]
A_inv:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
A_trans dot A:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
A dot A_trans:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Eigenvalues and eigenvectors**

In [0]:
A = np.array([[1,2,3],[5,4,6],[9,8,7]])
eigvals, eigvecs = np.linalg.eig(A)

print("eigenvalues:\n{}".format(eigvals))
print("eigenvectors:\n{}".format(eigvecs))

eigenvalues:
[15.16397149 -2.30607508 -0.85789641]
eigenvectors:
[[-0.24668682 -0.50330679  0.54359359]
 [-0.5421775  -0.3518559  -0.8137192 ]
 [-0.80323668  0.78922728  0.20583261]]


**Hessian matrix**

The Hessian is the second-order gradient $\nabla_A^2 f(A)$. It can also refer to the determinant of the Hessian matrix$det(\nabla_A^2 f(A))$.
The Jacobian is the first-order gradient $\nabla_A f(A)$.

**Singular value decomposition**

$A=U\Sigma V^{-1}$

In [0]:
A = np.array([[1,2,3],[5,4,6],[9,8,7]])
U, sigma, V = np.linalg.svd(A, full_matrices=True)

print("matrix A:\n{}".format(A))
print("matrix U:\n{}".format(U))
print("matrix sigma:\n{}".format(sigma))
print("matrix V:\n{}".format(V))

matrix A:
[[1 2 3]
 [5 4 6]
 [9 8 7]]
matrix U:
[[-0.20427138  0.64990738  0.73204754]
 [-0.51870339  0.56234361 -0.64398483]
 [-0.83019275 -0.51126321  0.22223846]]
matrix sigma:
[16.72332164  2.15323617  0.83311901]
matrix V:
[[-0.61408393 -0.54563911 -0.57024459]
 [-0.52931652 -0.25121094  0.81038083]
 [-0.58542715  0.79948172 -0.13455119]]
